// config/site.js
export const siteConfig = {
  // ── Doctor Details ─────────────────────────────────────────────────────
  name: "Dr. Roy",
  shortName: "Dr. Roy",
  title: "Dermatologist & Medical Aesthetic Practitioner",
  studio: "Skin Solution",
  tagline: "Advanced Aesthetic Dermatology",
  description:
    "Dr. Roy is a leading dermatologist and Medical Aesthetic Practitioner at Skin Solution, offering advanced skin and hair treatments in Lanji & Chennai.",
  url: "https://drroy.in",

  // ── Contact ────────────────────────────────────────────────────────────
  phone: "+91 90039 14390",
  email: "Dr.Shishir.Roy96@gmail.com",
  instagram: "https://instagram.com/drroy96studio",
  instagramHandle: "@drroy96studio",

  // ── Locations ──────────────────────────────────────────────────────────
  locations: [
    {
      city: "Lanji",
      label: "Lanji Clinic",
      address: "Skin Solution, Main Road, Lanji, Madhya Pradesh",
      mapUrl: "https://maps.google.com/?q=Lanji+Madhya+Pradesh",
      phone: "+91 90039 14390",
      hours: "Mon–Sat: 10:00 AM – 7:00 PM",
      isPrimary: true,
    },
    {
      city: "Chennai",
      label: "Chennai Clinic",
      address: "Skin Solution, Chennai, Tamil Nadu",
      mapUrl: "https://maps.google.com/?q=96+Studio+Chennai",
      phone: "+91 90039 14390",
      hours: "Tue & Thu: 11:00 AM – 5:00 PM",
      isPrimary: false,
    },
  ],

  // ── Credentials ────────────────────────────────────────────────────────
  credentials: [
    "MD Medical Cosmetology and Asthetic Injector",
    "Certified International Medical Competency Accreditation Council (IMCAC)",
    "Member of Global Aesthetic Safety Initiative United Kingdom",
    "Post Graduate Fellowship in Advanced Aesthetic Medicine",
    //add &#x1f1ec;&#x1f1e7; flag emoji at the end of the above line if possible
    "International Education Board Department of Aesthetic Medicine and Surgery UK ",
  ],
  experience: "8+ Years",
  patientsServed: "5000+",
  treatmentsDone: "10000+",
  rating: "4.9",

  // ── Services ───────────────────────────────────────────────────────────
  services: [
    {
      id: "prp-hair",
      title: "PRP Hair Therapy",
      category: "Hair Care",
      icon: "🧬",
      emoji: "💉",
      image: "/images/Advanced_hair_treatment2.jpeg",
      shortDesc:
        "Non-surgical Platelet-Rich Plasma treatment to restore hair density and stop hair loss.",
      fullDesc:
        "Platelet-Rich Plasma (PRP) therapy is a cutting-edge, non-surgical hair loss treatment. Your own blood is drawn, processed to concentrate the growth factors, and injected into the scalp to stimulate dormant follicles and promote natural hair regrowth.",
      benefits: [
        "Stimulates natural hair growth",
        "No surgery required",
        "Minimal downtime",
        "Safe, using your own blood",
        "Long-lasting results",
      ],
      duration: "45–60 min",
      sessions: "3–6 sessions",
      tag: "Most Popular",
      tagColor: "bg-gold text-navy-900",
    },
    {
      id: "acne-treatment",
      title: "Advanced Acne Treatment",
      category: "Skin Care",
      icon: "✨",
      emoji: "🔬",
      image: "/images/Acne_treatment3.jpeg",
      shortDesc:
        "Comprehensive acne management combining medical-grade therapies for clear, healthy skin.",
      fullDesc:
        "Our multi-modal acne treatment program addresses root causes — hormonal, bacterial, and inflammatory. Combining topical treatments, chemical peels, and advanced lasers for lasting clarity.",
      benefits: [
        "Clears active breakouts",
        "Reduces post-acne marks",
        "Prevents future flare-ups",
        "Personalized protocol",
        "Boosts confidence",
      ],
      duration: "30–45 min",
      sessions: "4–8 sessions",
      tag: "Highly Effective",
      tagColor: "bg-teal text-white",
    },
    {
      id: "skin-brightening",
      title: "Skin Brightening",
      category: "Skin Care",
      icon: "🌟",
      emoji: "💫",
      image: "/images/skin_brightning5.jpeg",
      shortDesc:
        "Target hyperpigmentation, uneven tone and dullness with our science-backed brightening protocols.",
      fullDesc:
        "Our skin brightening treatments address melasma, sun spots, and uneven skin tone using advanced chemical peels, laser therapy, and evidence-based topical agents for a luminous, even complexion.",
      benefits: [
        "Reduces dark spots",
        "Evens skin tone",
        "Boosts radiance",
        "Safe for all skin types",
        "Lasting results",
      ],
      duration: "30–45 min",
      sessions: "3–6 sessions",
      tag: null,
      tagColor: "",
    },
    {
      id: "anti-aging",
      title: "Anti-Aging Treatments",
      category: "Aesthetics",
      icon: "⏳",
      emoji: "🌿",
      image: "/images/anti_aging.jpeg",
      shortDesc:
        "Turn back the clock with dermal fillers, Botox, and skin rejuvenation protocols.",
      fullDesc:
        "Our comprehensive anti-aging program combines neuromodulators, dermal fillers, and skin-boosting treatments to restore youthful volume, smooth fine lines, and rejuvenate skin texture.",
      benefits: [
        "Smooths fine lines",
        "Restores volume",
        "Tightens skin",
        "Natural-looking results",
        "Minimal downtime",
      ],
      duration: "30–60 min",
      sessions: "1–3 sessions",
      tag: "Premium",
      tagColor: "bg-gold/20 text-gold border border-gold/40",
    },
    {
      id: "hair-care",
      title: "Hair Loss Management",
      category: "Hair Care",
      icon: "🪮",
      emoji: "💊",
      image: "/images/hair_loss_Management.png",
      shortDesc:
        "Comprehensive hair loss solutions including diagnosis, medical management, and advanced therapies.",
      fullDesc:
        "A thorough trichological evaluation followed by a customized treatment plan combining topical treatments, oral supplements, mesotherapy, and advanced PRP to address all causes of hair loss.",
      benefits: [
        "Root-cause diagnosis",
        "Medical management",
        "Mesotherapy available",
        "Scalp health focus",
        "Progress tracking",
      ],
      duration: "45 min",
      sessions: "Ongoing",
      tag: null,
      tagColor: "",
    },
    {
      id: "skincare-consult",
      title: "Personalized Skincare Consultation",
      category: "Consultation",
      icon: "📋",
      emoji: "🩺",
      image: "/images/Acne_treatment2.jpeg",
      shortDesc:
        "One-on-one session to build your perfect daily skincare routine with medical-grade guidance.",
      fullDesc:
        "A dedicated consultation to understand your skin type, concerns, lifestyle, and goals. Dr. Roy crafts a personalized daily routine including the right cleanser, moisturizer, and SPF 30+ sunscreen for your unique skin.",
      benefits: [
        "Personalized routine",
        "Product guidance",
        "SPF recommendations",
        "Follow-up support",
        "Skin analysis included",
      ],
      duration: "45–60 min",
      sessions: "1 session",
      tag: "Start Here",
      tagColor: "bg-navy/80 text-ivory border border-teal/30",
    },
    {
      id: "qs-laser",
      title: "QS Laser (Helios III)",
      category: "Laser Treatment",
      icon: "⚡",
      emoji: "✨",
      image: "/images/Tattoo_removal.jpeg",
      shortDesc:
        "Advanced Q-Switched laser treatment for pigmentation, tattoo removal, rejuvenation, and laser toning.",
      fullDesc:
        "The Helios III QS Laser is an advanced laser technology designed to target pigmentation, unwanted tattoos, dull skin, and uneven tone. It delivers safe and effective laser toning, rejuvenation, and facial treatments with minimal downtime.",
      benefits: [
        "Reduces pigmentation",
        "Effective tattoo removal",
        "Improves skin texture",
        "Brightens and rejuvenates skin",
        "Minimal downtime",
      ],
      duration: "30–60 min",
      sessions: "4–8 sessions",
      tag: "Advanced Laser",
      tagColor: "bg-purple-100 text-purple-700",
    },
    {
      id: "mnrf",
      title: "MNRF (Microneedling RF)",
      category: "Skin Care",
      icon: "📡",
      emoji: "🩹",
      image: "/images/skin_tightining.jpeg",
      shortDesc:
        "Radiofrequency microneedling treatment for acne scars, wrinkles, skin tightening, and open pores.",
      fullDesc:
        "Microneedling Radiofrequency (MNRF) combines collagen-inducing microneedling with radiofrequency energy to improve acne scars, stretch marks, wrinkles, enlarged pores, and overall skin texture.",
      benefits: [
        "Reduces acne scars",
        "Tightens skin",
        "Minimizes open pores",
        "Improves wrinkles and fine lines",
        "Boosts collagen production",
      ],
      duration: "45–60 min",
      sessions: "3–6 sessions",
      tag: "Skin Renewal",
      tagColor: "bg-rose-100 text-rose-700",
    },
    {
      id: "permanent-hair-removal",
      title: "Permanent Hair Removal",
      category: "Laser Treatment",
      icon: "🪒",
      emoji: "✨",
      image: "/images/Permanent_hair_reduction.webp",
      shortDesc:
        "Pain-free laser hair reduction using Alma Soprano Diode Laser for face and body.",
      fullDesc:
        "Our Alma Soprano Diode Laser technology provides safe, virtually pain-free, and long-lasting hair reduction for unwanted hair on the face, body, underarms, bikini line, and more.",
      benefits: [
        "Pain-free treatment",
        "Suitable for all skin types",
        "Long-lasting hair reduction",
        "No ingrown hairs",
        "Quick recovery time",
      ],
      duration: "20–60 min",
      sessions: "6–8 sessions",
      tag: "Pain-Free",
      tagColor: "bg-pink-100 text-pink-700",
    },
    {
      id: "micropigmentation",
      title: "Micropigmentation",
      category: "Aesthetics",
      icon: "🎨",
      emoji: "💋",
      image: "/images/lip_virtiligo.jpeg",
      shortDesc:
        "Advanced cosmetic pigmentation solutions for lips, scalp, and vitiligo correction.",
      fullDesc:
        "Micropigmentation is a semi-permanent cosmetic procedure used to enhance lips, restore scalp appearance, and camouflage vitiligo patches using specialized pigments and precision techniques.",
      benefits: [
        "Enhances natural appearance",
        "Scalp density illusion",
        "Vitiligo camouflage",
        "Long-lasting results",
        "Boosts confidence",
      ],
      duration: "60–120 min",
      sessions: "1–3 sessions",
      tag: "Cosmetic Enhancement",
      tagColor: "bg-amber-100 text-amber-700",
    },
    {
      id: "microblading",
      title: "Microblading",
      category: "Aesthetics",
      icon: "🖊️",
      emoji: "👁️",
      image: "/images/eye_brow.jpeg",
      shortDesc:
        "Semi-permanent eyebrow enhancement for fuller, natural-looking brows.",
      fullDesc:
        "Microblading is a precision eyebrow enhancement treatment that creates realistic hair-like strokes to improve brow shape, symmetry, and fullness with natural-looking results.",
      benefits: [
        "Natural-looking eyebrows",
        "Long-lasting enhancement",
        "Defines brow shape",
        "Saves daily makeup time",
        "Custom brow design",
      ],
      duration: "60–90 min",
      sessions: "1–2 sessions",
      tag: "Beauty Essential",
      tagColor: "bg-brown-100 text-brown-700",
    },
  ],

  // ── Appointment Slots ───────────────────────────────────────────────────
  timeSlots: [
    "10:00 AM",
    "10:30 AM",
    "11:00 AM",
    "11:30 AM",
    "12:00 PM",
    "12:30 PM",
    "02:00 PM",
    "02:30 PM",
    "03:00 PM",
    "03:30 PM",
    "04:00 PM",
    "04:30 PM",
    "05:00 PM",
    "05:30 PM",
    "06:00 PM",
    "06:30 PM",
  ],

  // ── Stats ──────────────────────────────────────────────────────────────
  stats: [
    { value: "8+", label: "Years Experience", icon: "🏆" },
    { value: "5K+", label: "Happy Patients", icon: "❤️" },
    { value: "10K+", label: "Treatments Done", icon: "✨" },
    { value: "4.9★", label: "Patient Rating", icon: "⭐" },
  ],

  // ── Testimonials ───────────────────────────────────────────────────────
  testimonials: [
    {
      name: "Priya M.",
      location: "Chennai",
      rating: 5,
      text: "My hair loss was making me lose confidence. After 4 PRP sessions with Dr. Roy, I can see significant regrowth. His expertise and caring approach made all the difference.",
      treatment: "PRP Hair Therapy",
    },
    {
      name: "Rajan K.",
      location: "Lanji",
      rating: 5,
      text: "Struggled with acne for years. Dr. Roy's treatment plan cleared my skin in 8 weeks. He explains everything clearly and actually listens to your concerns.",
      treatment: "Acne Treatment",
    },
    {
      name: "Ananya S.",
      location: "Chennai",
      rating: 5,
      text: "The skin brightening treatment gave me results I never thought possible. My melasma has significantly faded. Dr. Roy is a true expert in his field.",
      treatment: "Skin Brightening",
    },
    {
      name: "Vikram P.",
      location: "Lanji",
      rating: 5,
      text: "Came for anti-aging consultation, left with a completely personalized plan. The results after 2 sessions were remarkable. Highly professional clinic.",
      treatment: "Anti-Aging",
    },
    {
      name: "Deepa R.",
      location: "Chennai",
      rating: 5,
      text: "Dr. Roy's skincare consultation was eye-opening. He identified products I was using that were actually harming my skin. My complexion has transformed.",
      treatment: "Skincare Consultation",
    },
  ],

  // ── Gallery / Instagram posts (placeholder — replace with real data) ───
  galleryPosts: [
    {
      id: 1,
      type: "treatment",
      emoji: "💉",
      caption: "PRP Hair Therapy Session",
      url: "/images/face_treatment_before_after_Image1.png",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "248",
      category: "Hair",
    },
    {
      id: 2,
      type: "result",
      emoji: "✨",
      caption: "Skin Brightening Results",
      url: "/images/face_treatment_before_after_Image2.png",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "412",
      category: "Skin",
    },
    {
      id: 3,
      type: "tip",
      emoji: "☀️",
      caption: "Daily SPF Protection Tips",
      url: "/images/Tips_from_dermatologist.png",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "389",
      category: "Tips",
    },
    {
      id: 4,
      type: "clinic",
      emoji: "🏥",
      caption: "Advanced Hair Care Facility",
      url: "/images/hair_loss_Management.png",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "156",
      category: "Hair",
    },
    {
      id: 5,
      type: "treatment",
      emoji: "🔬",
      caption: "Permanent Hair Reduction Therapy",
      url: "/images/permanent_hair_reduction.webp",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "524",
      category: "Laser",
    },
    {
      id: 6,
      type: "tip",
      emoji: "💧",
      caption: "Morning Skincare Essentials",
      url: "/images/Tips_from_dermatologist_2.png",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "678",
      category: "Tips",
    },
    {
      id: 7,
      type: "result",
      emoji: "🌱",
      caption: "Hair Regrowth Transformation",
      url: "/images/permanent_hair_reduction2.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "891",
      category: "Hair",
    },
    {
      id: 8,
      type: "consultation",
      emoji: "👨‍⚕️",
      caption: "Personalized Skin Consultation",
      url: "/images/skin_brightening.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "203",
      category: "Skin",
    },
    {
      id: 9,
      type: "tip",
      emoji: "🧴",
      caption: "Choosing the Right Moisturizer",
      url: "/images/Tips_from_dermatologist_3.png",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "445",
      category: "Tips",
    },
    {
      id: 10,
      type: "tip",
      emoji: "🌿",
      caption: "Healthy Skin Habits",
      url: "/images/Tips_from_dermatologist_4.jpg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "445",
      category: "Tips",
    },
    {
      id: 11,
      type: "education",
      emoji: "🧬",
      caption: "The Science of Skincare",
      url: "/images/Tips_from_dermatologist_5.jpg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "567",
      category: "Tips",
    },
    {
      id: 12,
      type: "tip",
      emoji: "✨",
      caption: "Correct Skincare Layering Guide",
      url: "/images/Tips_from_dermatologist_6.jpg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "678",
      category: "Tips",
    },
    {
      id: 13,
      type: "nutrition",
      emoji: "🥗",
      caption: "Nutrition for Healthy Skin",
      url: "/images/Tips_from_dermatologist_7.jpg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Tips",
    },
    {
      id: 14,
      type: "result",
      emoji: "🌟",
      caption: "Advanced Skin Brightening Results",
      url: "/images/skin_brightining5.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
    {
      id: 15,
      type: "hair",
      emoji: "🪮",
      caption: "Advanced Hair Restoration Treatment",
      url: "/images/Advanced_hair_treatment.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Hair",
    },
    {
      id: 16,
      type: "skin",
      emoji: "💫",
      caption: "Glowing Skin Transformation",
      url: "/images/skin_brightining4.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
    {
      id: 17,
      type: "hair",
      emoji: "💆",
      caption: "Professional Hair Therapy Session",
      url: "/images/Advanced_hair_treatment2.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Hair",
    },
    {
      id: 18,
      type: "acne",
      emoji: "🩺",
      caption: "Advanced Acne Treatment Care",
      url: "/images/Acne_treatment.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
    {
      id: 19,
      type: "laser",
      emoji: "⚡",
      caption: "Laser Hair Reduction Results",
      url: "/images/Permanent_hair_reduction3.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Laser",
    },
    {
      id: 20,
      type: "result",
      emoji: "✨",
      caption: "Facial Rejuvenation Results",
      url: "/images/face_treatment_before_after_Image4.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
    {
      id: 21,
      type: "facial",
      emoji: "🌸",
      caption: "Healthy Skin Glow Treatment",
      url: "/images/face_treatment_before_after_Image3.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
    {
      id: 22,
      type: "skin",
      emoji: "💎",
      caption: "Radiant Skin Brightening Session",
      url: "/images/skin_brightining6.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
    {
      id: 23,
      type: "acne",
      emoji: "🔬",
      caption: "Acne Scar Improvement Journey",
      url: "/images/Acne_treatment3.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
    {
      id: 24,
      type: "acne",
      emoji: "✨",
      caption: "Clear Skin Acne Treatment Results",
      url: "/images/Acne_treatment4.jpeg",
      redirect_url: "https://www.instagram.com/dr.roy96studio/",
      likes: "789",
      category: "Skin",
    },
  ],

  aboutusPosts: [
    {
      id: 1,
      type: "treatment",
      emoji: "💉",
      caption: "Best Asthetic Award 2024 by Shilpa Shetty",
      url: "/images/personal/shilpa_shetty.jpeg",
    },
    {
      id: 2,
      type: "result",
      emoji: "✨",
      caption: "Best clinical cosmologist award 2022 by Mlaika Arora",
      url: "/images/personal/malika.jpeg",
    },
    {
      id: 3,
      type: "tip",
      emoji: "☀️",
      caption: "Best Deplomate award 2024",
      url: "/images/personal/Best_Deplomate_award_2024.jpeg",
    },
    {
      id: 4,
      type: "clinic",
      emoji: "🏥",
      caption: "International Education board UK",
      url: "/images/personal/International_Education_Board_UK.jpeg",
    },
    {
      id: 5,
      type: "treatment",
      emoji: "🔬",
      caption: "India's Best Medical Cosmetologist Award 2025",
      url: "/images/personal/India's_Best_Medical_Cosmetologist_Award_2025.jpeg",
    },
    {
      id: 6,
      type: "tip",
      emoji: "💧",
      caption: "Dr. Homer Rosales Mendoza",
      url: "/images/personal/Dr_Homer_Rosales_Mendoza.jpeg",
    },
    {
      id: 7,
      type: "result",
      emoji: "🌟",
      caption: "Dr. Jonathan",
      url: "/images/personal/Dr_Jonathan.jpeg",
    },
    {
      id: 8,
      type: "clinic",
      emoji: "👨‍⚕️",
      caption: "Dr. Jonathan ",
      url: "/images/personal/Dr_Jonathan1.jpeg",
    },
    {
      id: 9,
      type: "tip",
      emoji: "🧴",
      caption: "Dr. Prithac Reddy",
      url: "/images/personal/Dr_Prithac_Reddy.jpeg",
    },
    {
      id: 10,
      type: "tip",
      emoji: "🧴",
      caption: "Dr. Sangeeta Reddy",
      url: "/images/personal/Dr_Sangeeta_Reddy.jpeg",
    },
    {
      id: 11,
      type: "tip",
      emoji: "🧴",
      caption: "Dr. Vera",
      url: "/images/personal/Dr_Vera.jpeg",
    },
    {
      id: 12,
      type: "tip",
      emoji: "🧴",
      caption: "Photo from New York Conference 2024",
      url: "/images/personal/New_York_Conference_2024.jpeg",
    },
    {
      id: 13,
      type: "tip",
      emoji: "🧴",
      caption: "Photo from New York Conference 2023",
      url: "/images/personal/Photo_from_New_York_Conference_2023.jpeg",
    },
    {
      id: 14,
      type: "tip",
      emoji: "🧴",
      caption: "Japan Conference",
      url: "/images/personal/Japan_conference.jpeg",
    },
    {
      id: 15,
      type: "tip",
      emoji: "🧴",
      caption: "Dr.Roy in Magazine",
      url: "/images/personal/Dr_Roy_Magzine.jpeg",
    },
    {
      id: 16,
      type: "tip",
      emoji: "🧴",
      caption: "chhattisgarh health minister",
      url: "/images/personal/chhattisgarh_health_minister.jpeg",
    },
    {
      id: 17,
      type: "tip",
      emoji: "🧴",
      caption: "J.P. NAdda Sir",
      url: "/images/personal/JP_NAdda_Sir.jpeg",
    },
    {
      id: 18,
      type: "tip",
      emoji: "🧴",
      caption: "Dr. Ajai Rana",
      url: "/images/personal/Dr_Ajai_Rana.jpeg",
    },
    {
      id: 17,
      type: "tip",
      emoji: "🧴",
      caption: "Dr. David",
      url: "/images/personal/Dr_David.jpeg",
    },
  ],

  skincareTips: [
    {
      tip: "Always apply SPF 30+ sunscreen every morning, even indoors",
      icon: "☀️",
    },
    {
      tip: "Double cleanse at night to remove sunscreen and pollution",
      icon: "💧",
    },
    {
      tip: "Never skip moisturizer — even oily skin needs hydration",
      icon: "🧴",
    },
    {
      tip: "Introduce new actives slowly — one at a time, every 2 weeks",
      icon: "🔬",
    },
    {
      tip: "Drink 8–10 glasses of water daily for skin health from within",
      icon: "💦",
    },
  ],
};
